### ISSUE TITLE
Icon is Bigger that other icon mod

### ISSUE THREAD

**Issue by Potaro514** [BrenBronze/brenbronze-MC-Project-Issues-N-Suggestions#2]
Xaero's Naturalist Icons
ver. 1.20.1

Hi,
First, I want to say that I really appreciate the work put into "Xaero's Naturalist Icons" mod. It adds a fantastic level of detail and immersion to the game. However, I've noticed that the icons from this mod appear significantly larger compared to those from other mods like "Xaero Icon FA." It would be great if the icon sizes could be adjusted for better consistency.
Thanks for your hard work!

**Media**
![Screenshot (36)](https://github.com/BrenBronze/brenbronze-MC-Project-Issues-N-Suggestions/assets/78656989/26ba445e-16c0-422d-9d78-7dcee371b272)

> as you can see, duck icon is far more bigger than chicken icon (chicken icon from FA icon mod btw)

**Comment by BrenBronze** [comment]
im surprised i didnt notice this sooner.. 😅 thank you for your report, ive updated the resource pack and the files should be available on the [modrinth](https://modrinth.com/resourcepack/xaeros-naturalist-icons/versions) and [curseforge](https://www.curseforge.com/minecraft/texture-packs/xaeros-naturalist-icons/files/all?page=1&pageSize=20) sites shortly!
